We fix a few things:
 - we no longer need to set a variable where dynamic-colors has been
   checked out if we are running straight from the repo

 - we are using bash explicitly anyway, so let's use bash tests

 - documentation

diff --git a/bin/dynamic-colors b/bin/dynamic-colors
--- a/bin/dynamic-colors
+++ b/bin/dynamic-colors
@@ -16,7 +16,7 @@ Basic commands:
 
 Creating colorschemes:
   a,audit <colorscheme>   check <colorscheme> for undefined colors
-  c,create <colorscheme>  create a new colorscheme from scratch
+  n,new <colorscheme>     create a new colorscheme from scratch
 "
 
 die () {
@@ -26,22 +26,22 @@ die () {
 
 change_color () {
   case $1 in
-  color*)
-    send_osc 4 "${1#color};$2" ;;
-  foreground)
-    send_osc 10 "$2" ;;
-  background)
-    send_osc 11 "$2" ;;
-  cursor)
-    send_osc 12 "$2" ;;
-  mouse_foreground)
-    send_osc 13 "$2" ;;
-  mouse_background)
-    send_osc 14 "$2" ;;
-  highlight)
-    send_osc 17 "$2" ;;
-  border)
-    send_osc 708 "$2" ;;
+    color*)
+      send_osc 4 "${1#color};$2" ;;
+    foreground)
+      send_osc 10 "$2" ;;
+    background)
+      send_osc 11 "$2" ;;
+    cursor)
+      send_osc 12 "$2" ;;
+    mouse_foreground)
+      send_osc 13 "$2" ;;
+    mouse_background)
+      send_osc 14 "$2" ;;
+    highlight)
+      send_osc 17 "$2" ;;
+    border)
+      send_osc 708 "$2" ;;
   esac
 }
 
@@ -49,7 +49,7 @@ send_escape_sequence () {
   escape_sequence="$1"
 
   # wrap escape sequence when within a TMUX session
-  [ ! -z "$TMUX" ] && escape_sequence="${DSC}tmux;${ESC}${escape_sequence}${ESC}\\"
+  [[ -n "$TMUX" ]] && escape_sequence="${DSC}tmux;${ESC}${escape_sequence}${ESC}\\"
 
   printf "${escape_sequence}"
 }
@@ -69,26 +69,34 @@ OSC="${ESC}]"
 colors=( background foreground cursor mouse_background mouse_foreground highlight border color0 color1 color2 color3 color4 color5 color6 color7 color8 color9 color10 color11 color12 color13 color14 color15 )
 color_names=( black red green yellow blue magenta cyan white brblack brred brgreen bryellow brblue brmagenta brcyan brwhite )
 
-if [ -z "${DYNAMIC_COLORS_ROOT}" ]; then
-  DYNAMIC_COLORS_ROOT="${XDG_CACHE_HOME:-${HOME}/.cache}/dynamic-colors"
-  DYNAMIC_COLORS_SHARED=/usr/share/dynamic-colors
-  test -d $DYNAMIC_COLORS_ROOT || mkdir -p $DYNAMIC_COLORS_ROOT
-else
-  DYNAMIC_COLORS_ROOT="${DYNAMIC_COLORS_ROOT%/}"
-  DYNAMIC_COLORS_SHARED="${DYNAMIC_COLORS_ROOT}"
+# _ROOT is a bad name
+DYNAMIC_COLORS_ROOT="${XDG_CACHE_HOME:-${HOME}/.cache}/dynamic-colors"
+DYNAMIC_COLORS_ACTIVE="${DYNAMIC_COLORS_ROOT}/colorscheme"
+
+color_dir="$(dirname $(realpath $0))/../colorschemes"
+for d in "${color_dir}" /usr/share/dynamic-colors/colorschemes ; do
+  if [[ -d $d ]] ; then
+    COLORSCHEMES="${d}"
+    break
+  fi
+done
+if [[ -z "${COLORSCHEMES}" ]] ; then
+  echo "Unable to find directory with color schemes. Aborting!"
+  exit 1
 fi
-COLORSCHEMES="${DYNAMIC_COLORS_SHARED}/colorschemes"
+unset color_dir
 
 write_colorscheme_name () {
-  echo "$1" > "${DYNAMIC_COLORS_ROOT}/colorscheme"
+  test -d $DYNAMIC_COLORS_ROOT || mkdir -p $DYNAMIC_COLORS_ROOT
+  echo "$1" > "${DYNAMIC_COLORS_ACTIVE}"
 }
 
 load_colorscheme_name () {
-  head -1 "${DYNAMIC_COLORS_ROOT}/colorscheme"
+  head -1 "${DYNAMIC_COLORS_ACTIVE}"
 }
 
 init () {
-  [ ! -f "${DYNAMIC_COLORS_ROOT}/colorscheme" ] && return
+  [[ ! -f "${DYNAMIC_COLORS_ACTIVE}" ]] && return
   colorscheme_name=$(load_colorscheme_name)
   load_colorscheme "$colorscheme_name"
   set_colors
@@ -107,7 +115,7 @@ set_colors () {
 }
 
 load_colorscheme () {
-  [ ! -f "$COLORSCHEMES/$1.sh" ] && die "error: unknown colorscheme '$1'"
+  [[ ! -f "$COLORSCHEMES/$1.sh" ]] && die "error: unknown colorscheme '$1'"
   . "$COLORSCHEMES/$1.sh" # source colorscheme file
 }
 
@@ -122,11 +130,11 @@ audit () {
   load_colorscheme "$1"
   declare -a problems
   for color in ${colors[@]}; do
-    if [ ! ${!color} ]; then
+    if [[ ! ${!color} ]]; then
       problems=( "${problems[@]}" "\033[4m$color\033[0m is not defined" )
     fi
   done
-  if [ ${#problems[@]} -ne 0 ]; then
+  if [[ ${#problems[@]} -ne 0 ]]; then
     echo >&2 "$1:"
     for p in "${problems[@]}"
     do
@@ -137,30 +145,30 @@ audit () {
 }
 
 cycle() {
-    if [ -f "${DYNAMIC_COLORS_ROOT}/colorscheme" ]; then
-        current=`head -1 "${DYNAMIC_COLORS_ROOT}/colorscheme"`
-        found=false
-        cd "$COLORSCHEMES"
-        for file in *.sh; do
-            if [ $found = true ]; then
-                switch "${file%.sh}"
-                return
-            fi
-            if [ $file = "${current}.sh" ]; then
-                found=true
-            fi
-        done
-    fi
-
+  if [[ -f "${DYNAMIC_COLORS_ACTIVE}" ]]; then
+    current=`head -1 "${DYNAMIC_COLORS_ACTIVE}"`
+    found=false
     cd "$COLORSCHEMES"
     for file in *.sh; do
+      if [[ $found = true ]]; then
         switch "${file%.sh}"
-        break
+        return
+      fi
+      if [[ $file = "${current}.sh" ]]; then
+        found=true
+      fi
     done
+  fi
+
+  cd "$COLORSCHEMES"
+  for file in *.sh; do
+    switch "${file%.sh}"
+    break
+  done
 }
 
 list () {
-  [ ! -d "$COLORSCHEMES" ] && die "error: colorschemes directory '$COLORSCHEMES' doesn't exist"
+  [[ ! -d "$COLORSCHEMES" ]] && die "error: colorschemes directory '$COLORSCHEMES' doesn't exist"
   cd "$COLORSCHEMES"
   for file in *.sh; do
     echo "${file%.sh}"
@@ -177,7 +185,7 @@ edit () {
 }
 
 create () {
-  [ -f "$COLORSCHEMES/$1.sh" ] && die "error: colorscheme '$1' already exists"
+  [[ -f "$COLORSCHEMES/$1.sh" ]] && die "error: colorscheme '$1' already exists"
   output="# $1\n"
   for color in ${colors[@]}; do
     output+="\n$color=\"\""
@@ -197,31 +205,31 @@ help () {
 }
 
 case "$#" in
-0)
-  usage ;;
-*)
-  cmd="$1"
-  shift
-  case "$cmd" in
-  h|help)
-    help ;;
-  a|audit)
-    audit "$1" ;;
-  c|create)
-    [ $# -ne 1 ] && usage
-    create "$1" ;;
-  e|edit)
-    edit "$@" ;;
-  i|init)
-    init ;;
-  l|list)
-    list ;;
-  s|switch)
-    [ $# -ne 1 ] && usage
-    switch "$1" ;;
-  c|cycle)
-    cycle ;;
-  *)
+  0)
     usage ;;
-  esac
+  *)
+    cmd="$1"
+    shift
+    case "$cmd" in
+      h|help)
+        help ;;
+      a|audit)
+        audit "$1" ;;
+      c|cycle)
+        cycle ;;
+      e|edit)
+        edit "$@" ;;
+      i|init)
+        init ;;
+      l|list)
+        list ;;
+      n|new)
+        [ $# -ne 1 ] && usage
+        create "$1" ;;
+      s|switch)
+        [ $# -ne 1 ] && usage
+        switch "$1" ;;
+      *)
+        usage ;;
+    esac
 esac
